### ISSUE TITLE
Problematic warning in makeCurrentGwascat()

### ISSUE THREAD

**Issue by hpages** [vjcitn/gwascat#1]
Hi Vince,

I'm trying to learn about liftOver by following the [liftOver workflow](https://bioconductor.org/packages/3.15/workflows/vignettes/liftOver/inst/doc/liftov.html). I ran into the following problem when running the first code chunk:
```
> library(gwascat)
> cur = makeCurrentGwascat()
trying URL 'http://www.ebi.ac.uk/gwas/api/search/downloads/alternative'
downloaded 226.5 MB

                                                                                                                                                                formatting gwaswloc instance...    
NOTE: input data had non-ASCII characters replaced by '*'.
done.
Warning message:
One or more parsing issues, see `problems()` for details 
```
Ignore the fact that the warning doesn't "work" and that the suggested command needs to be replaced with `readr::problems()` ([which I just reported to the **readr** folks](https://github.com/tidyverse/readr/issues/1401)), it doesn't display anything:
```
> readr::problems()  # nothing gets displayed
```
Any idea what's going on?

Thanks,
H.

**Comment by vjcitn** [comment]
Thanks @hpages -- it is clear that I need to do some work to pass the problems back when such are encountered.  I will let you know.

**Comment by vjcitn** [comment]
For completeness, here is an example of the "problems" encountered when the problem data is shunted to a component of metadata() for our result.
```
> metadata(x)$probs
# A tibble: 558 × 5
     row   col expected actual               file                               
   <int> <int> <chr>    <chr>                <chr>                              
 1   266    24 a double 2162231-C            /private/var/folders/n4/p9th81md60…
 2  4906    24 a double 7769879-?            /private/var/folders/n4/p9th81md60…
 3  7785    13 a double 18418999 x 65869047  /private/var/folders/n4/p9th81md60…
 4  8458    13 a double 47803382 x 165891269 /private/var/folders/n4/p9th81md60…
 5  8462    13 a double 33690933 x 71013515  /private/var/folders/n4/p9th81md60…
 6  9232    13 a double 80464197 x 111811826 /private/var/folders/n4/p9th81md60…
 7  9794    13 a double 92573550 x 142088761 /private/var/folders/n4/p9th81md60…
 8 10324    13 a double 17734133 x 4574206   /private/var/folders/n4/p9th81md60…
 9 10325    13 a double 12115842 x 28077607  /private/var/folders/n4/p9th81md60…
10 10338    13 a double 38601324 x 135896972 /private/var/folders/n4/p9th81md60…
# … with 548 more rows
```
Why so many problems?  Well, there is creativity in the filing of the records for the different studies.  When readr::read_tsv gets something that doesn't belong, according to the definition of column types that was given, a problem is recorded.  The number of problems grows over time, if the gwascat staff does not fix the aberrant records.

**Comment by vjcitn** [comment]
The records with " x " are observations of phenotype association with pairs of loci.  How should these unusual records be handled?  I did not make a decision to date.

**Comment by vjcitn** [comment]
I did not change the parsing process or the returned data, but I have moved the "problems" records, when such are produced, to the probs component of metadata of the returned `gwaswloc` instance.  This was done for both 3.15 and devel.

**Comment by hpages** [comment]
Thanks for this improvement.
